itmproject/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('browse/', views.browse, name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
]

itmproject/item/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import Category, Item

def browse(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.all()

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if category_id:
        items = items.filter(category_id=category_id)

    return render(request, 'item/browse.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'item/detail.html', { 
        'item' : item
        })

itmproject/item/templates/item/browse.html
{% extends 'core/base.html' %}

{% block title %}Browse{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:browse' %}">
                <input name="query" class="w-full py-4 px-6 border" type="text" value="{{ query }}" placeholder="Search for a product...">

                <button class="mt-2 py-3 px-6 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-300">Search</button>
                {% if query %}
                <a href="{% url 'item:browse' %}" class="text-sm px-2 text-gray-500 underline hover:text-gray-700">Clear Search</a>
                {% endif %}
            </form>

            <hr class="my-6">

            <p class="font-semibold">Filter by Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 rounded-xl{% if category.id == category_id %} underline{% endif %}">
                        <a href="{% url 'item:browse' %}?query{{ query }}&category={{ category.id }}" class="text-sm text-gray-700 hover:underline">
                            {{ category.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <ul>
                <li><a href="{% url 'item:browse' %}" class="mt-2 py-2 px-2 inline-block bg-gray-400 text-white text-sm font-semibold rounded-xl">Clear Filters</a></li>
            </ul>
        </div>
        <div class="col-span-3">
            {% if items %}
                <div class="grid grid-cols-3 gap-3">
                    {% for item in items %}
                        <div class="bg-white shadow h-full">
                            <a href="{% url 'item:detail' item.id %}" class="flex flex-col h-full">
                                <div class="h-64 overflow-hidden">
                                    {% if item.image %}
                                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full h-full object-cover">
                                    {% else %}
                                        <div class="flex items-center justify-center h-full text-gray-400">
                                            <p>No image available</p>
                                        </div>
                                    {% endif %}
                                </div>

                                <div class="p-4 flex flex-col justify-between flex-grow">
                                    <h2 class="text-lg font-semibold mb-2">{{ item.name }}</h2>
                                    <p class="text-gray-500">Suggested Price: {{ item.price }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p class="text-center text-gray-500 text-lg mt-12">No results match your search.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

itmproject/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{ item.name }{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6 max-w-4xl mx-auto">
  <div class="col-span-3">
    <img src="{{ item.image.url }}" class="w-full max-w-md mx-auto">
  </div>

  <div class="col-span-2 p-4 bg-blue-200 text-center">
    <h1 class="mb-4 text-xl font-semibold">{{ item.name }}</h1>
    <p class="text-base text-black"><strong>Suggested Price: </strong>{{ item.price }}</p>

    {% if item.description %}
        <p class="text-base text-gray-700 text-left mt-8 px-4">
            {{ item.description }}
        </p>
    {% endif %}

        <div class="flex items-center space-x-2">
          <label class="text-gray-700 px-4 py-8"><strong>Quantity:</strong></label>
          <input type="number" class="w-20 border border-gray-300 px-2 py-1 rounded" value="1" min="1" />
        </div>

    <a href="#" class="inline-block mt-12 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-300 w-64 text-center">Add to Quotation</a>
    <a href="{% url 'item:browse' %}" class="inline-block mt-12 px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-300 w-64 text-center">Return to Store Page</a>
  </div>
</div>
{% endblock %}