itmproject/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

from .forms import LoginForm

app_name = 'core'

urlpatterns = [
	path('', views.index, name='index'),
	path('contact/',views.contact, name='contact'),
	path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

itmproject/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

itmproject/core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm

from django.contrib.auth import logout

def index(request):
    items = Item.objects.all()[0:3]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories' : categories, 
        'items' : items,
    })

def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:	
		form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form
	})

def logout_view(request):
    logout(request)
    return redirect('core:index')

def contact(request):
    return render(request, 'core/contact.html')

itmproject/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="uft-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Papers&Pens</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <div class="flex flex-col items-start">
                <a href="/" class="text-xl font-semibold">Papers&amp;Pens</a>
                <span class="text-xs text-black">Home Page</span>
            </div>

            <div class="space-x-6">
                <a href="{% url 'item:browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse Products</a>
                {% if request.user.is_authenticated %}
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-300">View My Quotation Form</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-black text-white rounded-xl hover:bg-gray-400">Log Out</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-300">Sign Up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-black text-white rounded-xl hover:bg-gray-400">Log In</a>
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-blue-500">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-white">About Us</h3>

                <p class="text-base text-white">We are a family-run business passionate about producing the highest quality papers and pens.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-white">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:contact' %}" class="text-base text-gray-300 hover:text-gray-200">Contact Us</a></li>
                    <li><a href="#" class="text-base text-gray-300 hover:text-gray-200">Privacy Policy</a></li>
                    <li><a href="#" class="text-base text-gray-300 hover:text-gray-200">Terms of Use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

itmproject/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="text-center py-12 px-4">
    <h1 class="text-4xl font-bold mb-4">Papers and Pens</h1>
    <p class="text-gray-600 text-base max-w-xl mx-auto">
        Explore our curated collection of quality stationery and office supplies — from well-crafted paper to smooth-flowing pens, perfect for writing, planning, and creating.
    </p>
    </div>


    <div class="mt-5 px-6 py-12 bg-blue-100">
        <h2 class="mb-12 text-2xl text-center">Latest Products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div class="bg-white shadow h-full">
                    <a href="{% url 'item:detail' item.id %}" class="flex flex-col h-full">
                        <div class="h-64 overflow-hidden">
                            {% if item.image %}
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full h-full object-cover">
                            {% else %}
                                <div class="flex items-center justify-center h-full text-gray-400">
                                    <p>No image available</p>
                                </div>
                            {% endif %}
                        </div>

                        <div class="p-4 flex flex-col justify-between flex-grow">
                            <h2 class="text-lg font-semibold mb-2">{{ item.name }}</h2>
                            <p class="text-gray-500">Suggested Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

itmproject/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-½ my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <div class="mt-6 space-y-4">
            <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-300 rounded-xl text-white">
                Submit
            </button>

            <p class="text-gray-600 font-medium">or</p>

            <a href="{% url 'core:signup' %}" class="inline-block py-4 px-8 text-lg bg-gray-500 text-white rounded-xl text-center hover:bg-gray-400">
                Create an Account
            </a>
        </div>
    </form>
</div>
{% endblock %}

itmproject/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-½ my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username (No spaces)</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password (min. 8 characters, must have at least 1 letter, ensure password is not too common or similar to your personal detials)</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-300 rounded-xl text-white">Submit</button>
    </form>

    <a href="{% url 'core:login' %}" class="mt-4 inline-block py-4 px-8 text-lg bg-gray-500 text-white rounded-xl hover:bg-gray-400">Log In to Existing Account</a>
</div>
{% endblock %}